#
# Makefile for Turbo C++ 3.0
#
# $Id$
#

.AUTODEPEND

.PATH.obj = .

#		*Translator Definitions*
CC	= tcc +TEST.CFG
TASM	= TASM
TLIB	= tlib
TLINK	= tlink
LIBPATH	= \TC\LIB
INCLUDEPATH = ..\INCLUDE;\TC\INCLUDE


#		*Implicit Rules*
.c.obj:
  $(CC) -c {$< }

#		*List Macros*

OBJS	= test.obj orat.obj format.obj arith.obj flag.obj picture.obj \
	  random.obj

#		*Explicit Rules*
test.exe: test.cfg $(OBJS)
	$(CC) -etest @&&|
test.obj
orat.obj
format.obj
arith.obj
flag.obj
picture.obj
random.obj
..\..\lib\sarien.lib
|


#		*Individual File Dependencies*


#		*Compiler Configuration File*
#
# Turbo C++ Version 3.00 Copyright (c) 1992 Borland International
# Syntax is: TCC [ options ] file[s]     * = default; -x- = turn switch x off
#  -1      80186/286 Instructions    -2      80286 Protected Mode Inst.
#  -Ax     Disable extensions        -B      Compile via assembly
#  -C      Allow nested comments     -Dxxx   Define macro
#  -Exxx   Alternate Assembler name  -G      Generate for speed
#  -Ixxx   Include files directory   -K      Default char is unsigned
#  -Lxxx   Libraries directory       -M      Generate link map
#  -N      Check stack overflow      -O      Optimize jumps
#  -P      Force C++ compile         -Qxxx   Memory usage control
#  -S      Produce assembly output   -Txxx   Set assembler option
#  -Uxxx   Undefine macro            -Vx     Virtual table control
#  -X      Suppress autodep. output  -Yx     Overlay control
#  -Z      Suppress register reloads -a      Generate word alignment
#  -b    * Treat enums as integers   -c      Compile only
#  -d      Merge duplicate strings   -exxx   Executable file name
#  -fxx    Floating point options    -gN     Stop after N warnings
#  -iN     Max. identifier length    -jN     Stop after N errors
#  -k      Standard stack frame      -lx     Set linker option
#  -mx     Set Memory Model          -nxxx   Output file directory
#  -oxxx   Object file name          -p      Pascal calls
#  -r    * Register variables        -u    * Underscores on externs
#  -v      Source level debugging    -wxxx   Warning control
#  -y      Produce line number info  -zxxx   Set segment names

test.cfg: makefile.tc
  copy &&|
-ml
-a
-N
-O
-Z
-d
-r
-vi-
-w-ret
-w-nci
-w-inl
-w-par
-w-cpt
-w-dup
-w-pia
-w-ill
-w-sus
-w-ext
-w-ias
-w-ibc
-w-pre
-w-nst
-n.
-I$(INCLUDEPATH)
-DVERSION="0.8.0"
-D__interrupt=interrupt
-D__far=far
-L$(LIBPATH)
-Ff
| test.cfg

