# $Id$

XCFLAGS	= -I ../../include
OBJS	= main.o
DFILES	= Makefile $(OBJS:.o=.m) SarienIcon.icns
CFILES	=
DDIRS	= sdl #English.lproj French.lproj
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Version
include ../../../Rules

