# $Id$

XCFLAGS	= -I../../include -I/home/claudio/emu/microwin/src/include/
OBJS	= nanox.o
DFILES	= Makefile $(OBJS:.o=.c)
CFILES	=
DDIRS	=
LIB	= ../../../lib/libagi.a

all: $(LIB)

include ../../../Rules

