# $Id$

XCFLAGS	= -I../../include
OBJS	= dummy.o
DFILES	= Makefile $(OBJS:.o=.c) Makefile.wat Makefile.dj
CFILES	=
DDIRS	=
XDFILES	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Rules

