
XCFLAGS =
OBJS	=
DFILES	= Makefile AUTHORS BUGS Changelog COPYING README.agi README.sdl \
	  README.svgalib README.unix README.win32 README.ports README.dga \
	  TODO agispecs.sgml
CFILES	=
DDIRS	=
XDFILES =
LIB	=

all:

include ../Rules

