
XCFLAGS = -I../include
OBJS	=
DFILES	= Makefile
CFILES	=
# XoXus: Modified this to include "svgalib" at end
DDIRS	= msdos win32 unix # beos macos
XDFILES =
LIB	=

all:
	(cd $(FILEIO_DRIVER); $(MAKE) all)

include ../../Rules

