
XCFLAGS	= -I../../include -I../../core/win32 -Wno-implicit-int
OBJS	= win32.o
DFILES	= Makefile $(OBJS:.o=.c)
CFILES	=
DDIRS	=
XDFILES	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Rules

