# $Id$

XCFLAGS = -I../include
OBJS	=
DFILES	= Makefile
CFILES	=
DDIRS	= msdos sdl x11 svgalib allegro win32 photon dive macos amiga \
	  script dc directx cocoa
XDFILES =
LIB	=

all:
	(cd $(CONSOLE_DRIVER); $(MAKE) all)

include ../../Rules

