
XCFLAGS = -I../include
OBJS	=
DFILES	= Makefile
CFILES	=
# XoXus: Modified this to include "svgalib" at end
DDIRS	= msdos sdl x11 svgalib win32 photon dive macos amiga
XDFILES =
LIB	=

all:
	(cd $(CONSOLE_DRIVER); $(MAKE) all)

include ../../Rules

