# $Id$

XCFLAGS	= -I ../../include
OBJS	= SDLmain.o MyWindowController.o
DFILES	= Makefile $(OBJS:.o=.m) $(OBJS:.o=.h)
CFILES	=
DDIRS	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../../Version
include ../../../../Rules

