#
# Makefile for Watcom C/C++ v10.6
#

include $(HOME)/src/graphics/msdos/djgpp.dep

OBJS = djgpp.o

all: driver.a

driver.a: $(OBJS)
	ar rsv driver.a $(OBJS)

clean:
	@if exist *.bak @del *.bak
	@if exist *.o @del *.o
	@if exist *.a @del *.a
