# $Id $

XCFLAGS	= -I../../include
OBJS	=
DFILES	= Makefile Makefile.wat pcvga.c pccga.c pccga.asm djgpp.c djgpp.h \
	  Makefile.dj
CFILES	=
DDIRS	=
XDFILES	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Version
include ../../../Rules

