
XCFLAGS	= -I../../include
OBJS	=
DFILES	= Makefile Makefile.wat ibm.c ibm.h djgpp.c djgpp.h watcom.dep \
	  Makefile.dj
CFILES	=
DDIRS	=
XDFILES	=
LIB	= ../../../lib/libagi.a

all: $(LIB)

include ../../../Version
include ../../../Rules

