#
# Makefile for DJGPP + Allegro
#

include $(HOME)/src/graphics/msdos/djgpp.dep

OBJS = djgpp.o

all: driver.a

driver.a: $(OBJS)
	ar rsv driver.a $(OBJS)

clean:
	@if exist *.bak @del *.bak
	@if exist *.o @del *.o
	@if exist *.a @del *.a
