#
# Makefile for DJGPP v2
#
# $Id$
#

include $(TOPDIR)/Rules.dj

OBJS = djgpp.o

all: driver.a

driver.a: $(OBJS)
	ar rsv driver.a $(OBJS)

clean:
	@if exist *.bak del *.bak
	@if exist *.o del *.o
	@if exist *.a del *.a
