# $Id$

XCFLAGS = -I../include
OBJS	=
DFILES	= Makefile
CFILES	=
DDIRS	= oss sdl dummy alsa bsd solaris sgi win32 freebsd qnx dart
XDFILES =
LIB	=

all:
	(cd $(SOUND_DRIVER); $(MAKE) all)

include ../../Rules

