#
# Makefile for DJGPP v2
#
# $Id$
#

include $(TOPDIR)/Rules.dj

OBJS = fileglob.o

all: fileglob.a

fileglob.a: $(OBJS)
	ar rsv fileglob.a $(OBJS)

clean:
	@if exist *.a @del *.a
	@if exist *.o @del *.o
	@if exist *.bak @del *.bak
