# $Id$

XCFLAGS =
OBJS	=
DFILES	= Makefile crown.h dcmain.c dcui.c dcui.h dcwrapper.c font.c \
	  gsi.c gsi.h gslogo.c gslogo.h image.h portdefs.h pvrutils.c \
	  pvrutils.h util.c util.h
CFILES	=
DDIRS	=
XDFILES =
LIB	=

all:

include ../../../Rules

