# $Id$

XCFLAGS	= -I../../include
OBJS	= SarienWindow.o SarienApplication.o SarienView.o cocoa.o
DFILES	= Makefile $(OBJS:.o=.m) $(OBJS:.o=.h)
CFILES	=
DDIRS	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Rules

