# $Id$

XCFLAGS	= -I../../include -I/home/claudio/emu/microwin/src/include/
OBJS	= script.o
DFILES	= Makefile $(OBJS:.o=.c) README demo2.script
CFILES	=
DDIRS	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Rules

