# $Id$

XCFLAGS =
OBJS	=
DFILES	= Makefile agi.h getopt.h iff.h keyboard.h logic.h lzw.h menu.h \
	  opcodes.h picture.h rand.h savegame.h sound.h sarien.h portdefs.h \
	  view.h win32.h console.h text.h graphics.h sprite.h list.h config.h
CFILES	=
DDIRS	=
XDFILES =
LIB	=

all:

include ../../Rules

