# $Id$

XCFLAGS =
OBJS	=
DFILES	= Makefile agi.h getopt.h gfx.h iff.h keyboard.h logic.h lzw.h menu.h \
	  objects.h opcodes.h picture.h rand.h savegame.h sound.h sarien.h \
	  view.h win32.h words.h console.h
CFILES	=
DDIRS	=
XDFILES =
LIB	=

all:

include ../../Rules

