# $Id$

XCFLAGS =
OBJS	=
DFILES	= Makefile PocketSarien.rc PocketSarien.vco PocketSarien.vcp \
	  SarienImages.bmp browse.cpp browse.h newres.h portdefs.h \
	  resource.h wince.cpp winmain.cpp
CFILES	=
DDIRS	= gapi missing
XDFILES =
LIB	=

all:

include ../Rules

